plugins:
  - jekyll-remote-theme

remote_theme: chromatical/jekyll-materialdocs

#https://github.com/chromatical/jekyll-materialdocs/
title: Documention
logo: ./assets/logo.jpg
copyright: GemsTracker
